{"name": "test_login_courier_with_wrong_password_error_expected", "status": "passed", "steps": [{"name": "Проверка ошибки при неправильном заполнении поля password", "status": "passed", "steps": [{"name": "Авторизовать курьера", "status": "passed", "parameters": [{"name": "body", "value": "{'login': 'ninjaTester', 'password': '12345'}"}], "start": 1725462726475, "stop": 1725462727079}], "start": 1725462726475, "stop": 1725462727081}], "start": 1725462726475, "stop": 1725462727082, "uuid": "3ead03e5-00d2-47af-ae98-8e6469f3c001", "historyId": "1031ed3fa38bb19e077e64fbfbcbf725", "testCaseId": "1031ed3fa38bb19e077e64fbfbcbf725", "fullName": "tests.test_login_courier.TestLoginCourier#test_login_courier_with_wrong_password_error_expected", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "Dolbobook"}, {"name": "thread", "value": "19956-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}